services:
  blog:
    build: .
    container_name: blog
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history
    depends_on:
      - db
      - redis
    networks:
      - dev-environment_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.rule=Host(`blog.docker.localhost`)"
      - "traefik.http.routers.blog.tls=true"
      - "traefik.http.services.blog.loadbalancer.server.port=3000"
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=changeme
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - dev-environment_default
  redis:
    image: redis
    volumes:
      - redis_data:/data
    networks:
      - dev-environment_default

volumes:
  pg_data:
  redis_data:
  bundle:

networks:
  dev-environment_default:
    external: true